---
title: "Funding Model"
author: "A Abbott"
date: "12/3/2018"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---

```{r setup, message = FALSE}
library(tidyverse)
library(tidyquant)
library(DT)
library(lubridate)
library(ggplot2)
library(flexdashboard)
source("pensionFuns.R")
source("fundingModelLib.R")
```

Sidebar {.sidebar}
======================================================

```{r sidebar}
pl <- planList()

fluidRow(column(
  10,
  selectInput(
    "state",
    "Select a state:",
    choices = levels(pl$state),
    selected = "Arkansas"
  )
))
fluidRow(column(10,
                uiOutput("plan")))
fluidRow(
  column(10,
         numericInput("n", "Years to project", 35,
                      min = 1, max = 100)))
fluidRow(
  column(10,
         numericInput("pgr", "Payroll Growth Rate %", 2.75,
                      min = 0, max = 10)))
fluidRow(
  column(10,
         numericInput("current_dr", "Current Discount Rate %", 7.5,
                      min = 3, max = 10)))
fluidRow(
  column(10,
         numericInput("future_dr", "Future Discount Rate %", 7.5,
                      min = 3, max = 10)))
fluidRow(
  column(10,
         numericInput("existing_gnc", "Existing Employee Gross Normal Cost Rate %", 11.75,
                      min = 0, max = 20)))
fluidRow(
  column(10,
         numericInput("rehired_gnc", "Rehired Employee Gross Normal Cost Rate %", 11.75,
                      min = 0, max = 20)))
fluidRow(
  column(10,
         numericInput("new_gnc", "New Employee Gross Normal Cost Rate %", 11.75,
                      min = 0, max = 20)))

actionButton("go", "Submit")

# Built with Shiny by RStudio
h5(
  "Built with",
  img(src = "https://www.rstudio.com/wp-content/uploads/2014/04/shiny.png", height = "30px"),
  "by",
  img(src = "https://www.rstudio.com/wp-content/uploads/2014/07/RStudio-Logo-Blue-Gray.png", height = "30px"),
  "."
)

plans <- reactive({
  pl %>% subset(state == input$state) %>% select(display_name)
})

dataset <- eventReactive(input$go, {
  pullData(input$plan) %>% 
    spreadData()
})

selected_data <- eventReactive(input$go, {
  all_data <- selectedData(dataset())
  initial <- last(all_data) %>%
    mutate_if(is.character, as.numeric) %>%
    mutate(
      rehi_payroll = 104073,
      new_payroll = 0,
      existing_payroll = payroll
    ) %>%
    mutate(
      payroll_total = existing_payroll + rehi_payroll
    ) %>%
    mutate(
      uaal = aal - actuarial_assets,
      funded_ratio = actuarial_assets / aal,
      `ADEC Contribution Rates` = adec / payroll_total,
      `Actual Contribution Rates (Statutory)` = emp_cont / payroll_total
    )
  date_min <- initial$valuation_date[1]
  date_max <- date_min + years(input$n)
  all_dates <- seq(date_min, date_max, by = "year")
  new_df <- data.frame(list(valuation_date = all_dates))
  merged_df <- merge(new_df, initial, all = T)
  merged_df %>%
    mutate(year = lag(year(valuation_date), default = first(year) - 1) + 1,
           contribution_fy = year + 2) %>%
    mutate(
      payroll_total = payrollGrowth(., pgr = input$pgr),
      payroll_rehi = payrollGrowth(., y = "rehi_payroll", pgr = input$pgr),
      payroll_existing = payrollExistingGrowth(.)
    ) %>%
    mutate(payroll_new = payroll_total - payroll_rehi - payroll_existing) %>%
    select(-c(payroll, rehi_payroll, new_payroll, existing_payroll))
})

output$plan <- renderUI({
  selectInput("plan",
              "Select a plan:",
              choices = plans(),
              selected = "Arkansas Teachers Retirement Plan")
})
   
```

Pension Funding Model
===============================================


Row {.tabset .tabset-fade}
-----------------------------------------------


### Data

```{r combined}
 renderDT({
    dataTableFM(selected_data())
 })

```
